global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "config-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["config-server:8888"]

  - job_name: "discovery-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["discovery-service:8761"]

  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["auth-service:8081"]

  - job_name: "product-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["product-service:8082"]

  - job_name: "order-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["order-service:8083"]

  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: "cart-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["cart-service:5001"]

  - job_name: "payment-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["payment-service:5002"]
