server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fathy2028/marketco
          default-label: main
          search-paths: config-server/src/main/resources/config
        native:
          search-locations: classpath:/config/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fathy2028/marketco
          default-label: main
          search-paths: config-server/src/main/resources/config
        native:
          search-locations: classpath:/config/


