server:
  port: 8083

spring:
  application:
    name: order-service
  config:
    import: configserver:http://config-server:8888
  cloud:
    config:
      enabled: true
      uri: http://config-server:8888
  datasource:
    url: jdbc:postgresql://postgres-order-db:5432/orderdb
    username: order_user
    password: order_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq-broker
    port: 5672
    username: rabbitmq_user
    password: rabbitmq_password
    virtual-host: /
  security:
    jwt:
      secret: mySecretKey123456789012345678901234567890
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  instance:
    prefer-ip-address: true
