server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      enabled: true
      uri: http://config-server:8888
  datasource:
    url: jdbc:postgresql://postgres-auth-db:5432/authdb
    username: auth_user
    password: auth_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  instance:
    prefer-ip-address: true
